Move capture to main folder
This is because we will get an error if not: JPM [error]   Message:
RequirementError: The `contentScriptFile` option must be a local URL or
an array of URLs.